//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS20.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\tool\\ImageMagik\\")]
        public string ImageMagikWorkingDirectory {
            get {
                return ((string)(this["ImageMagikWorkingDirectory"]));
            }
            set {
                this["ImageMagikWorkingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\tool\\ImageMagik\\logo-main.png ")]
        public string WatermarkImgPath {
            get {
                return ((string)(this["WatermarkImgPath"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Progra~1\\WinRAR\\rar.exe")]
        public string RarPath {
            get {
                return ((string)(this["RarPath"]));
            }
            set {
                this["RarPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Content\\zipdesc.txt")]
        public string ZipDescFile {
            get {
                return ((string)(this["ZipDescFile"]));
            }
            set {
                this["ZipDescFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Content\\GameData\\")]
        public string DstGameDirPath {
            get {
                return ((string)(this["DstGameDirPath"]));
            }
            set {
                this["DstGameDirPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Game_Base")]
        public string SrcGameDirPath {
            get {
                return ((string)(this["SrcGameDirPath"]));
            }
            set {
                this["SrcGameDirPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Content\\FileShare\\")]
        public string FileShareFolder {
            get {
                return ((string)(this["FileShareFolder"]));
            }
            set {
                this["FileShareFolder"] = value;
            }
        }
    }
}
