//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameID { get; set; }
        public string TitleRu { get; set; }
        public string TitleEn { get; set; }
        public string CatalogName { get; set; }
        public int YearPublishing { get; set; }
        public float Rating { get; set; }
        public string Lang { get; set; }
        public string Descript { get; set; }
        public string NumOfPlayers { get; set; }
        public string NumOfSuggested { get; set; }
        public string SuggestedAges { get; set; }
        public string Acquaintance { get; set; }
        public string PlayingTime { get; set; }
        public string Components { get; set; }
        public int ImageGameplay { get; set; }
        public int ImageScans { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
