//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subscribe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.GameTag = new HashSet<GameTag>();
        }
    
        public int GameID { get; set; }
        public string TitleRu { get; set; }
        public string TitleEn { get; set; }
        public string CatalogName { get; set; }
        public int YearPublishing { get; set; }
        public float Rating { get; set; }
        public string Lang { get; set; }
        public string Descript { get; set; }
        public string NumOfPlayers { get; set; }
        public string NumOfSuggested { get; set; }
        public string SuggestedAges { get; set; }
        public string Acquaintance { get; set; }
        public string PlayingTime { get; set; }
        public string Components { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameTag> GameTag { get; set; }
    }
}
