//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subscribe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscribe
    {
        public int SubscribeID { get; set; }
        public string Email { get; set; }
        public string TagList { get; set; }
    }
}
